services:
  - type: web
    name: c-toglb
    env: node
    buildCommand: echo "No build needed"
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

